export const RealtimeConfig = {
  RATE_LIMIT_ACTIVITY_START_PER_MIN: 'WS_RATE_LIMIT_ACTIVITY_START_PER_MIN',
  RATE_LIMIT_WINDOW_MS: 'WS_RATE_LIMIT_WINDOW_MS',
  STREAM_MAX_BUFFER_BYTES: 'WS_STREAM_MAX_BUFFER_BYTES',
  STREAM_MAX_SESSIONS: 'WS_STREAM_MAX_SESSIONS',
  BACKPRESSURE_SAMPLES_PER_SEC: 'WS_BACKPRESSURE_SAMPLES_PER_SEC',
  STREAM_FLUSH_INTERVAL_MS: 'WS_STREAM_FLUSH_INTERVAL_MS',
} as const;
